name: Sync Avalanche L1s

on:
  workflow_dispatch:
  schedule:
    # every day at 02:00 UTC
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1) grab your code
      - uses: actions/checkout@v4

      # 2) install Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3) install requests into _that_ same python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip requests

      # 4) actually run your script
      - name: Run sync script
        env:
          ATTIO_TOKEN:   ${{ secrets.940191a34faae94b961302f41ab965989573bc613fff7a609834441467babd80 }}
          ATTIO_OBJ:     ${{ secrets.companies }}
          ATTIO_LIST_ID: ${{ secrets.9a23136a-5390-4c8f-b7f7-4cd3f9267a00 }}
        run: python sync_l1s.py
