name: Sync Avalanche L1s
on:
  schedule:
    cron: '0 2 * * *'  # daily
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run script
        run: python sync_l1s.py
        env:
          ATTIO_TOKEN: ${{ secrets.ATTIO_TOKEN }}
          ATTIO_OBJ: ${{ secrets.ATTIO_OBJ }}
          ATTIO_LIST_ID: ${{ secrets.ATTIO_LIST_ID }}
