# .github/workflows/sync.yml
name: Sync Avalanche L1s

on:
  schedule:
    cron:  '0 2 * * *'  # every night at 02:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Run sync script
        env:
          ATTIO_TOKEN:   ${{ secrets.ATTIO_TOKEN }}
          ATTIO_OBJ:     ${{ secrets.ATTIO_OBJ }}
          ATTIO_LIST_ID: ${{ secrets.ATTIO_LIST_ID }}
        run: python sync_l1s.py
